const _gptTodo = [
  'do the same prompt for "Nicholas Santos"',
  'do the same prompt for "Daiya Seto"',
  'do the same prompt for "Ilya Shymanovich"',
  'do the same prompt for "Coleman M Stewart"',
  'do the same prompt for "Zac Stubblety-cook"',
  'do the same prompt for "Szebasztian Szabo"',
  'do the same prompt for "Florian Wellbrock"',
  'do the same prompt for "Diesel Willier"',
  'do the same prompt for "Minna Atherton"',
  'do the same prompt for "Mireia BELMONTE Garcia"',
  'do the same prompt for "Cate Campbell"',
  'do the same prompt for "Evgeniia Chikunova"',
  'do the same prompt for "Katherine C Douglass"',
  'do the same prompt for "Siobhan Haughey"',
  'do the same prompt for "Torri Huske"',
  'do the same prompt for "Lillia C King"',
  'do the same prompt for "Bingjie Li"',
  'do the same prompt for "Margaret Macneil"',
  'do the same prompt for "Summer Mcintosh"',
  'do the same prompt for "Ruta Meilutyte"',
  'do the same prompt for "Mafalda Rocha Mendes"',
  `do the same prompt for "Mollie O'Callaghan"`,
  'do the same prompt for "Benedetta Pilato"',
  'do the same prompt for "Amandine Pittet"',
  'do the same prompt for "Tatjana R Schoenmaker"',
  'do the same prompt for "Sarah Sjostrom"',
  'do the same prompt for "Regan E Smith"',
  'do the same prompt for "Ariarne Titmus"',
  'do the same prompt for "Sarah Wellbrock"',
  'do the same prompt for "Yufei Zhang"',
  'do the same prompt for "Cesar Cielo"',
  'do the same prompt for "Lin Zhang"',
  'do the same prompt for "Yang Sun"',
  'do the same prompt for "Lukas Breiter"',
  'do the same prompt for "Lennon Schmied"',
  'do the same prompt for "Hannah Breiter"',
  'do the same prompt for "Julia Hinnerks"',
  'do the same prompt for "Sarina Liesch"',
  'do the same prompt for "Fiona Liesch"',
  'do the same prompt for "Céline Müller"',
  'do the same prompt for "Talia Jordan"',
  'do the same prompt for "Léna Ecoffey"',
  'do the same prompt for "Yannick Knab"',
  'do the same prompt for "Severin Oberli"',
  'do the same prompt for "Kilian Roppel"',
  'do the same prompt for "Giordana Graf"',
  'do the same prompt for "Xenia Blumin"',
];
