import { sql } from '@vercel/postgres';
import 'dotenv/config';
import type { Swimmer } from './schema';
import { SwimmerTable } from './schema';
import { db } from '.';

const seededSwimmers: Swimmer[] = [
  {
    surname: 'Cameron',
    lastname: 'Mcevoy',
    club: 'Somerville',
    weight: 75,
    height: 185,
    birthdate: new Date('1994-05-12'),
    bio: 'An accomplished swimmer has consistently demonstrated dedication and skill throughout his career. His impressive achievements in the pool, including numerous national and international accolades, highlight a commitment to excellence in the sport. The disciplined training regimen and sportsmanship exhibited by this individual serve as positive examples for aspiring athletes. As he continues to contribute to the swimming community, his impact on the sport remains significant, fostering admiration for his accomplishments and dedication to the pursuit of excellence. In evaluating contributions, it is important to recognize the influence on the broader swimming landscape and the inspiration provided to fellow athletes.',
    instagram: 'https://www.instagram.com/cam_mcevoy/',
    tiktok: 'https://www.tiktok.com/@cammcevoy',
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kathleen',
    lastname: 'Ledecky',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kaylee',
    lastname: 'Mckeown',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Jing',
    lastname: 'Zhao',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Hunter',
    lastname: 'Armstrong',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Thomas',
    lastname: 'Ceccon',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kyle',
    lastname: 'Chalmers',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Caeleb',
    lastname: 'Dressel',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Andrii',
    lastname: 'Govorov',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Hamza',
    lastname: 'Niyazi',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Tomoru',
    lastname: 'Honda',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kliment',
    lastname: 'Kolesnikov',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mitchell',
    lastname: 'Larkin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Leon',
    lastname: 'Marchand',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kristof',
    lastname: 'Milak',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ryan F',
    lastname: 'Murphy',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Adam',
    lastname: 'Peaty',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'David',
    lastname: 'Popovici',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kirill',
    lastname: 'Prigoda',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Haiyang',
    lastname: 'Qin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Emre',
    lastname: 'Sakci',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Nicholas',
    lastname: 'Santos',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Daiya',
    lastname: 'Seto',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ilya',
    lastname: 'Shymanovich',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Coleman M',
    lastname: 'Stewart',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Zac',
    lastname: 'Stubblety-cook',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Szebasztian',
    lastname: 'Szabo',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Florian',
    lastname: 'Wellbrock',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Diesel',
    lastname: 'Willier',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Minna',
    lastname: 'Atherton',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mireia BELMONTE',
    lastname: 'Garcia',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Cate',
    lastname: 'Campbell',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Evgeniia',
    lastname: 'Chikunova',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Katherine C',
    lastname: 'Douglass',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Siobhan',
    lastname: 'Haughey',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Torri',
    lastname: 'Huske',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lillia C',
    lastname: 'King',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Bingjie',
    lastname: 'Li',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Margaret',
    lastname: 'Macneil',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Summer',
    lastname: 'Mcintosh',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ruta',
    lastname: 'Meilutyte',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mafalda Rocha',
    lastname: 'Mendes',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mollie',
    lastname: "O'Callaghan",
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Benedetta',
    lastname: 'Pilato',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Amandine',
    lastname: 'Pittet',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Tatjana R',
    lastname: 'Schoenmaker',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Sarah',
    lastname: 'Sjostrom',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Regan E',
    lastname: 'Smith',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ariarne',
    lastname: 'Titmus',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Sarah',
    lastname: 'Wellbrock',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Yufei',
    lastname: 'Zhang',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Cesar',
    lastname: 'Cielo',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lin',
    lastname: 'Zhang',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Yang',
    lastname: 'Sun',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lukas',
    lastname: 'Breiter',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lennon',
    lastname: 'Schmied',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Hannah',
    lastname: 'Breiter',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Julia',
    lastname: 'Hinnerks',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Sarina',
    lastname: 'Liesch',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Fiona',
    lastname: 'Liesch',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Céline',
    lastname: 'Müller',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Talia',
    lastname: 'Jordan',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Léna',
    lastname: 'Ecoffey',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Yannick',
    lastname: 'Knab',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Severin',
    lastname: 'Oberli',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kilian',
    lastname: 'Roppel',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Giordana',
    lastname: 'Graf',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Xenia',
    lastname: 'Blumin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
];

async function seed(): Promise<void> {
  await db
    .insert(SwimmerTable)
    .values(seededSwimmers)
    .onConflictDoNothing({
      target: [SwimmerTable.surname, SwimmerTable.lastname],
    });
  await sql.end();
}

void seed();
