import { sql } from '@vercel/postgres';
import 'dotenv/config';
import type { Swimmer } from './schema';
import { SwimmerTable } from './schema';
import { db } from '.';

const seededSwimmers: Swimmer[] = [
  {
    surname: 'Cameron',
    lastname: 'Mcevoy',
    club: 'Somerville',
    weight: 75,
    height: 185,
    birthdate: new Date('1994-05-12'),
    bio: 'An accomplished swimmer has consistently demonstrated dedication and skill throughout his career. His impressive achievements in the pool, including numerous national and international accolades, highlight a commitment to excellence in the sport. The disciplined training regimen and sportsmanship exhibited by this individual serve as positive examples for aspiring athletes. As he continues to contribute to the swimming community, his impact on the sport remains significant, fostering admiration for his accomplishments and dedication to the pursuit of excellence. In evaluating contributions, it is important to recognize the influence on the broader swimming landscape and the inspiration provided to fellow athletes.',
    instagram: 'https://www.instagram.com/cam_mcevoy/',
    tiktok: 'https://www.tiktok.com/@cammcevoy',
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kathleen',
    lastname: 'Ledecky',
    club: "Nation's Capital Swim Club",
    weight: 73,
    height: 183,
    birthdate: new Date('1997-03-17'),
    bio: 'Kathleen Ledecky, born on March 17, 1997, is an American competitive swimmer renowned for her remarkable achievements in the sport. Hailing from Bethesda, Maryland, Ledecky rose to prominence with her outstanding performances in freestyle events. She made her Olympic debut at the 2012 London Games, capturing gold in the 800-meter freestyle at just 15 years old. Subsequently, Ledecky continued to dominate the swimming world, earning numerous world records and additional Olympic gold medals in the 200, 400, and 800-meter freestyle events. Her dedication and prowess have solidified her status as one of the most accomplished swimmers of her generation.',
    instagram: 'https://www.instagram.com/katieledecky',
    tiktok: 'https://twitter.com/katieledecky',
    youtube: null,
    twitter: 'https://twitter.com/katieledecky',
  },
  {
    surname: 'Kaylee',
    lastname: 'Mckeown',
    club: 'Griffith University',
    weight: 60,
    height: 175,
    birthdate: new Date('2001-07-12'),
    bio: 'Born on July 11, 2001, in Brisbane, Australia, Kaylee McKeown is a highly accomplished swimmer recognized for her excellence in backstroke events. McKeown made her mark on the international stage with a breakout performance at the 2021 Tokyo Olympics, where she secured three gold medals in the 100-meter and 200-meter backstroke, as well as the 4x100-meter medley relay. Her precision and speed in the water have earned her praise, establishing McKeown as a rising star in the world of competitive swimming. With a promising career ahead, she continues to be a notable figure in Australian swimming.',
    instagram: 'https://www.instagram.com/kaylee_mckeown/',
    tiktok: 'https://www.tiktok.com/@kaylee.mckeown',
    youtube: null,
    twitter: 'https://twitter.com/ee_oly',
  },
  {
    surname: 'Jing',
    lastname: 'Zhao',
    club: 'Zhejiang',
    weight: 59,
    height: 176,
    birthdate: new Date('1990-12-31'),
    bio: "Zhao Jing, born on May 12, 1995, in Shijiazhuang, China, is a distinguished Chinese swimmer specializing in backstroke events. She gained international recognition for her exceptional performances, particularly at the 2012 London Olympics, where she clinched a gold medal in the 100-meter backstroke. Zhao's precision in the water and her ability to compete at the highest level have solidified her status as a key figure in Chinese swimming. Throughout her career, she has consistently demonstrated skill and determination, contributing to her nation's success on the global stage.",
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Hunter',
    lastname: 'Armstrong',
    club: 'Canton City Swimming',
    weight: 82,
    height: 203,
    birthdate: new Date('2001-01-24'),
    bio: "Hunter Armstrong, born on May 13, 2001, is an American swimmer known for his proficiency in individual medley and backstroke events. Hailing from Dover, Ohio, Armstrong gained prominence on the national stage before making his Olympic debut at the 2020 Tokyo Games. At the Olympics, he showcased his talent by competing in the 100-meter backstroke and contributing to the United States' success in the 4x100-meter medley relay, earning a gold medal. Armstrong's dedication to his craft and impressive performances underscore his potential as a rising star in American swimming.",
    instagram: 'https://www.instagram.com/hunterarmstrong_/',
    tiktok: null,
    youtube: null,
    twitter: 'https://twitter.com/ArmstrongH_',
  },
  {
    surname: 'Thomas',
    lastname: 'Ceccon',
    club: 'GS Fiamme Oro',
    weight: 80,
    height: 197,
    birthdate: new Date('2001-01-27'),
    bio: "Thomas Ceccon, born on September 5, 2001, in Verona, Italy, is an accomplished Italian swimmer celebrated for his achievements in both backstroke and freestyle events. Rising to prominence in the international swimming scene, Ceccon made a significant impact at the 2020 Tokyo Olympics, securing a bronze medal in the 100-meter backstroke and contributing to Italy's success in the 4x100-meter medley relay. His versatility and competitive spirit have garnered attention, establishing Ceccon as a promising talent within Italian swimming. With a bright future ahead, he continues to make notable contributions to his country's success in the pool.",
    instagram: 'https://www.instagram.com/ceccon_thomas',
    tiktok: null,
    youtube: 'https://www.youtube.com/@thomasceccon1433',
    twitter: null,
  },
  {
    surname: 'Kyle',
    lastname: 'Chalmers',
    club: 'Marion Swimming Club',
    weight: 93,
    height: 194,
    birthdate: new Date('1998-06-25'),
    bio: "Kyle Chalmers, born on June 25, 1998, in Adelaide, Australia, is a highly acclaimed Australian swimmer specializing in freestyle events. Chalmers gained widespread recognition at the 2016 Rio Olympics, where he captured the gold medal in the 100-meter freestyle, showcasing his exceptional speed and skill in the water. Known for his powerful and determined swimming style, Chalmers has continued to excel on the international stage, earning additional accolades in various competitions. His dedication to the sport and impressive performances have solidified his status as one of Australia's top swimmers and a notable presence in global swimming competitions.",
    instagram: 'https://www.instagram.com/kyle_chalmers3/',
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Caeleb',
    lastname: 'Dressel',
    club: 'Cali Condors',
    weight: 91,
    height: 191,
    birthdate: new Date('1996-08-16'),
    bio: "Caeleb Dressel, born on August 16, 1996, in Green Cove Springs, Florida, is an accomplished American swimmer renowned for his versatility and exceptional performances in sprint events. Dressel rose to prominence at the 2016 Rio Olympics, where he earned two gold medals as part of the United States' relay teams. He further solidified his status as a swimming sensation at the 2020 Tokyo Olympics, clinching an unprecedented five gold medals, including victories in the 50-meter and 100-meter freestyle events. Dressel's remarkable speed, technique, and consistency make him a dominant force in the world of competitive swimming, earning him widespread acclaim and admiration.",
    instagram: 'https://www.instagram.com/caelebdressel',
    tiktok: null,
    youtube: null,
    twitter: 'https://twitter.com/caelebdressel',
  },
  {
    surname: 'Andrii',
    lastname: 'Govorov',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Hamza',
    lastname: 'Niyazi',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Tomoru',
    lastname: 'Honda',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kliment',
    lastname: 'Kolesnikov',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mitchell',
    lastname: 'Larkin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Leon',
    lastname: 'Marchand',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kristof',
    lastname: 'Milak',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ryan F',
    lastname: 'Murphy',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Adam',
    lastname: 'Peaty',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'David',
    lastname: 'Popovici',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kirill',
    lastname: 'Prigoda',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Haiyang',
    lastname: 'Qin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Emre',
    lastname: 'Sakci',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Nicholas',
    lastname: 'Santos',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Daiya',
    lastname: 'Seto',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ilya',
    lastname: 'Shymanovich',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Coleman M',
    lastname: 'Stewart',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Zac',
    lastname: 'Stubblety-cook',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Szebasztian',
    lastname: 'Szabo',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Florian',
    lastname: 'Wellbrock',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Diesel',
    lastname: 'Willier',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Minna',
    lastname: 'Atherton',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mireia BELMONTE',
    lastname: 'Garcia',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Cate',
    lastname: 'Campbell',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Evgeniia',
    lastname: 'Chikunova',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Katherine C',
    lastname: 'Douglass',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Siobhan',
    lastname: 'Haughey',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Torri',
    lastname: 'Huske',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lillia C',
    lastname: 'King',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Bingjie',
    lastname: 'Li',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Margaret',
    lastname: 'Macneil',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Summer',
    lastname: 'Mcintosh',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ruta',
    lastname: 'Meilutyte',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mafalda Rocha',
    lastname: 'Mendes',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Mollie',
    lastname: "O'Callaghan",
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Benedetta',
    lastname: 'Pilato',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Amandine',
    lastname: 'Pittet',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Tatjana R',
    lastname: 'Schoenmaker',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Sarah',
    lastname: 'Sjostrom',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Regan E',
    lastname: 'Smith',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Ariarne',
    lastname: 'Titmus',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Sarah',
    lastname: 'Wellbrock',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Yufei',
    lastname: 'Zhang',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Cesar',
    lastname: 'Cielo',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lin',
    lastname: 'Zhang',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Yang',
    lastname: 'Sun',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lukas',
    lastname: 'Breiter',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Lennon',
    lastname: 'Schmied',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Hannah',
    lastname: 'Breiter',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Julia',
    lastname: 'Hinnerks',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Sarina',
    lastname: 'Liesch',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Fiona',
    lastname: 'Liesch',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Céline',
    lastname: 'Müller',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Talia',
    lastname: 'Jordan',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Léna',
    lastname: 'Ecoffey',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Yannick',
    lastname: 'Knab',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Severin',
    lastname: 'Oberli',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Kilian',
    lastname: 'Roppel',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Giordana',
    lastname: 'Graf',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    surname: 'Xenia',
    lastname: 'Blumin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
];

async function seed(): Promise<void> {
  await db
    .insert(SwimmerTable)
    .values(seededSwimmers)
    .onConflictDoNothing({
      target: [SwimmerTable.surname, SwimmerTable.lastname],
    });
  await sql.end();
}

void seed();
