import { sql } from '@vercel/postgres';
import 'dotenv/config';
import type { Swimmer } from './schema';
import { SwimmerTable } from './schema';
import { db } from '.';

const seededSwimmers: Swimmer[] = [
  {
    id: 1,
    surname: 'Cameron',
    lastname: 'Mcevoy',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 2,
    surname: 'Kathleen',
    lastname: 'Ledecky',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 3,
    surname: 'Kaylee',
    lastname: 'Mckeown',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 4,
    surname: 'Jing',
    lastname: 'Zhao',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 5,
    surname: 'Hunter',
    lastname: 'Armstrong',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 6,
    surname: 'Thomas',
    lastname: 'Ceccon',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 7,
    surname: 'Kyle',
    lastname: 'Chalmers',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 8,
    surname: 'Caeleb',
    lastname: 'Dressel',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 9,
    surname: 'Andrii',
    lastname: 'Govorov',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 10,
    surname: 'Hamza',
    lastname: 'Niyazi',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 11,
    surname: 'Tomoru',
    lastname: 'Honda',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 12,
    surname: 'Kliment',
    lastname: 'Kolesnikov',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 13,
    surname: 'Mitchell',
    lastname: 'Larkin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 14,
    surname: 'Leon',
    lastname: 'Marchand',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 15,
    surname: 'Kristof',
    lastname: 'Milak',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 16,
    surname: 'Ryan F',
    lastname: 'Murphy',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 17,
    surname: 'Adam',
    lastname: 'Peaty',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 18,
    surname: 'David',
    lastname: 'Popovici',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 19,
    surname: 'Kirill',
    lastname: 'Prigoda',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 20,
    surname: 'Haiyang',
    lastname: 'Qin',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 21,
    surname: 'Emre',
    lastname: 'Sakci',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 22,
    surname: 'Nicholas',
    lastname: 'Santos',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 23,
    surname: 'Daiya',
    lastname: 'Seto',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 24,
    surname: 'Ilya',
    lastname: 'Shymanovich',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 25,
    surname: 'Coleman M',
    lastname: 'Stewart',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 26,
    surname: 'Zac',
    lastname: 'Stubblety-cook',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 27,
    surname: 'Szebasztian',
    lastname: 'Szabo',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 28,
    surname: 'Florian',
    lastname: 'Wellbrock',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 29,
    surname: 'Diesel',
    lastname: 'Willier',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 30,
    surname: 'Minna',
    lastname: 'Atherton',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 31,
    surname: 'Mireia BELMONTE',
    lastname: 'Garcia',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 32,
    surname: 'Cate',
    lastname: 'Campbell',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 33,
    surname: 'Evgeniia',
    lastname: 'Chikunova',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 34,
    surname: 'Katherine C',
    lastname: 'Douglass',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 35,
    surname: 'Siobhan',
    lastname: 'Haughey',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 36,
    surname: 'Torri',
    lastname: 'Huske',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 37,
    surname: 'Lillia C',
    lastname: 'King',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 38,
    surname: 'Bingjie',
    lastname: 'Li',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 39,
    surname: 'Margaret',
    lastname: 'Macneil',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 40,
    surname: 'Summer',
    lastname: 'Mcintosh',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 41,
    surname: 'Ruta',
    lastname: 'Meilutyte',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 42,
    surname: 'Mafalda Rocha',
    lastname: 'Mendes',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 43,
    surname: 'Mollie',
    lastname: "O'Callaghan",
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 44,
    surname: 'Benedetta',
    lastname: 'Pilato',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 45,
    surname: 'Amandine',
    lastname: 'Pittet',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 46,
    surname: 'Tatjana R',
    lastname: 'Schoenmaker',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 47,
    surname: 'Sarah',
    lastname: 'Sjostrom',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 48,
    surname: 'Regan E',
    lastname: 'Smith',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 49,
    surname: 'Ariarne',
    lastname: 'Titmus',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 50,
    surname: 'Sarah',
    lastname: 'Wellbrock',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
  {
    id: 51,
    surname: 'Yufei',
    lastname: 'Zhang',
    club: null,
    weight: null,
    height: null,
    birthdate: null,
    bio: null,
    instagram: null,
    tiktok: null,
    youtube: null,
    twitter: null,
  },
];

async function seed(): Promise<void> {
  await db
    .insert(SwimmerTable)
    .values(seededSwimmers)
    .onConflictDoNothing({ target: SwimmerTable.id });
  await sql.end();
}

void seed();
